# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b8b53d464102acb44dc56604397cb99fcc6db2e3171e950f2512267953f53ced1ec71b2da70139536f3079917bb804485d5a2f5e79b2e2c73c7eae7c993408

test:
  secret_key_base: 87762c2b0d09e90c99a46750b0b80e4855e9f57cc9c962710dd01db68250f71fd4d0d0e80e429d2524c19981aa69470163d700ad9174bf1ec96038af7836b036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
